### ISSUE TITLE
Note input responds to both on and off messages

### ISSUE THREAD

**Issue by dromer** [vulcu/dahlia#17]
You probably want to add `[stripnote]` (bugfix on hvcc pending) so you can treat the note-off separately.

**Comment by vulcu** [comment]
thanks! So, the envelope generator in `voice.pd` already tests for note on (velocity > 0) or noteoff (velocity == 0) and uses that to send the correct line values for the relevant envelope stage ('attack' or 'release') to the `|hv.vline~|` component. What is the bug in hvcc, is it not handling this correctly somehow?

**Comment by vulcu** [comment]
also, really appreciate your feedback on these issues!

**Comment by dromer** [comment]
I didn't test this with hvcc yet, but I tried the pd patch and it creates notes on both on and off events :shrug: 

In hvcc you currently have to use `[pack f f]` to send the note+velocity into the left inlet of `[stripnote]`, but I have a pending fix so that you can send the velocity to the right inlet as well: https://github.com/Wasted-Audio/hvcc/issues/149

And no problem! I randomly stumbled on your project and figured I'd give some input to help it move forward :)

**Comment by vulcu** [comment]
yup, definitely a bug -- the portamento patch is retriggering the note during note-off events, looks like a copy-paste error on my part. Should be limited to the monophonic voicing. Great catch! :)
